### PR TITLE
Feature add margin spacing support

### LINKED ISSUE #59: Handle tileset margins and spacing
TileSets can have margins and tile spacing.  This is currently unhandled, so tile sprites will be incorrect if either of these values are set.

The calculation is done in `utilities.go`, but the calling code is in `tile.go` in the function `Draw` which already takes a `*Tileset` parameter, shouldn't be difficult to calculate the offsets

### PR DESCRIPTION
**Pull request by perber**
**Checklist**
Ensure all of these are completed before opening the PR:
 - [X] Run `goimports`
 - [X] Read the [contribution guide](https://github.com/bcvery1/tilepix/blob/master/CONTRIBUTING.md)
 - [X] Read the [code of conduct](https://github.com/bcvery1/tilepix/blob/master/CODE_OF_CONDUCT.md)
 - [X] Read the [coding standards](https://github.com/bcvery1/tilepix/blob/master/CODING_STANDARDS.md)
 - [X] Tests run with `-race`
 - [x] Tests written to cover any new code
 - [X] Added yourself to the [contributors file](https://github.com/bcvery1/tilepix/blob/master/CONTRIBUTORS.md)

**Describe the changes**
Added support for margin and spacing

**Closing issues**
Resolves #59

### CODE REVIEW

**Comment by bcvery1** [comment]
It looks like this is failing for older versions of Go.  This may just be a Travis issue

**Comment by bcvery1** [comment]
@perber I'm happy to merge this once tests are passing. I'll take a look at the reason behind the failure when I can, but if you think you can figure it out, please go ahead

**Comment by perber** [comment]
@bcvery1 I haven't added a test yet. Should I provide one ?

**Comment by perber** [comment]
Hi, 
https://github.com/golang/go/issues/31293 

There are two possible solutions. Stick to previous go version, than the builds will be successuful or update to a new ubuntu distro. I would prefer to update to a new distribution.

**Comment by bcvery1** [comment]
Yeah, I agree that the change in distro is the best choice here.  Thanks for taking the time to look further into this issue than was the scope of the original issue!

I'll merge this now

**Pull request merged**
